apiVersion: v1
kind: Service
metadata:
  name: book-store-rating-ms
  labels:
    app: book-store-rating-ms
spec:
  type: LoadBalancer
  ports:
  - port: 8200
    targetPort: 8200
    protocol: TCP
  selector:
    app: book-store-rating-ms