apiVersion: v1
kind: Service
metadata:
  name: book-store-gateway-ms
  labels:
    app: book-store-gateway-ms
spec:
  type: LoadBalancer
  ports:
  - port: 8090
    targetPort: 8090
    protocol: TCP
  selector:
    app: book-store-gateway-ms