apiVersion: skaffold/v2alpha4
kind: Config
metadata:
  name: book-store-gateway
build:
  artifacts:
  - image: luiscortes/book-store-gateway-ms
    jib: {}
deploy:
  kubectl:
    manifests:
    - deployment.yml
    - service.yml
portForward:
- resourceType: deployment
  resourceName: myDep
  namespace: mynamespace  # 
  port: 8090 # 
  localPort: 8090 # *Optional*
