spring:
    application:
        name: book-store-ms
    datasource:        url: jdbc:h2:mem:bookstoredb
        driver-class-name: org.h2.Driver
        username: sa
        password: 
    jpa:        database-platform: org.hibernate.dialect.H2Dialect

server:
    port: 8100

eureka:
    client:
        service-url:
            default-zone: http://localhost:8761/eureka/
    instance:
        lease-renewal-interval-in-seconds: 10
        metadata-map:
            instance-id: ${vcap.application.instance_id:${spring.application.name}:${spring.application.instance_id:${server.port}}}
