apiVersion: v1
kind: Service
metadata:
  name: book-store-inventory-ms
  labels:
    app: book-store-inventory-ms
spec:
  type: LoadBalancer
  ports:
  - port: 8100
    targetPort: 8100
    protocol: TCP
  selector:
    app: book-store-inventory-ms