spring:
    datasource:
        url: jdbc:h2:mem:bookstoredb
        driver-class-name: org.h2.Driver
        username: sa
        password: 
    jpa:
        database-platform: org.hibernate.dialect.H2Dialect
    sleuth:
        trace-id128: true
        sampler:
            probability: 1.0
        feign:
            enabled: true
        zuul:
            enabled: true
    zipkin:
        base-url: http://localhost:9441


eureka:
    instance:
        lease-renewal-interval-in-seconds: 10
        metadata-map:
            instance-id: ${vcap.application.instance_id:${spring.application.name}:${spring.application.instance_id:${server.port}}}

feign:
  client:
    config:
      feignName:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: full

bookstore:
    message: Welcome to Funny Book Store!!!!!

welcome: Welcome To Funny Book Store
