spring:
    application:
        name: book-store-rating-ms
    datasource:
        url: jdbc:h2:mem:bookstoreratingdb
        driver-class-name: org.h2.Driver
        username: sa
        password: 
    jpa:
        database-platform: org.hibernate.dialect.H2Dialect
    sleuth:
        trace-id128: true
        sampler:
            probability: 1.0
        feign:
            enabled: true
        zuul:
            enabled: true
    zipkin:
        base-url: http://localhost:9441

feign:
  client:
    config:
      feignName:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: full

server:
    port: 8200

eureka:
    client:
        serviceUrl:
            defaultZone: http://book-store-registry-server:8761/eureka/
        registerWithEureka: false
        fetchRegistry: true
    instance:
        preferIpAddress: true
        leaseRenewalIntervalInSeconds: 10
        metadataMap:
            instanceId: ${vcap.application.instance_id:${spring.application.name}:${spring.application.instance_id:${server.port}}}
